'use client';
import {useEffect,useState,type FormEvent} from 'react';
import {gestao,mensagem} from '../../lib/gestao/client';
import type {Comunicado} from '../../lib/gestao/types';
import {Field,Select,TextArea,buttonClass,secondaryClass,panelClass,Badge} from './Shared';
export default function Comunicados({segmento,total}:{segmento:Record<string,unknown>;total:number}){
 const [items,setItems]=useState<Comunicado[]>([]),[editing,setEditing]=useState<Comunicado|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[ok,setOk]=useState('');
 async function load(){setItems(await gestao<Comunicado[]>('comunicados'));}
 useEffect(()=>{let live=true;gestao<Comunicado[]>('comunicados').then(r=>{if(live)setItems(r);}).catch(e=>{if(live)setError(mensagem(e));});return()=>{live=false;};},[]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const form=e.currentTarget;setBusy(true);setError('');setOk('');try{await gestao('comunicado_salvar',{...Object.fromEntries(new FormData(form)),id:editing?.id,updated_at:editing?.updated_at,segmento:editing?.segmento??segmento});setEditing(null);form.reset();setOk('Rascunho salvo. Nenhuma mensagem foi enviada.');await load();}catch(e){setError(mensagem(e));}finally{setBusy(false);}}
 return <section className={panelClass}><div className="mb-4 flex flex-wrap items-center gap-3"><h2 className="text-xl font-bold text-gray-900">Comunicados e segmentação</h2><Badge>Somente rascunhos</Badge></div><p className="mb-4 text-sm text-gray-500">Os filtros do CRM definem o público: {total} cadastro(s) na seleção atual. Prepare o texto para um envio futuro por e-mail ou WhatsApp.</p><form key={editing?.id??'new'} onSubmit={save}><fieldset disabled={busy} className="grid gap-4 md:grid-cols-2"><Field label="Assunto *" name="titulo" required maxLength={200} defaultValue={editing?.titulo}/><Select label="Canal futuro" name="canal" options={['E-mail','WhatsApp']} defaultValue={editing?.canal??'E-mail'}/><div className="md:col-span-2"><TextArea label="Mensagem" name="texto" value={editing?.texto}/></div></fieldset><div className="mt-4 flex gap-3"><button disabled={busy} className={buttonClass}>{busy?'Salvando…':editing?'Salvar rascunho':'Salvar rascunho com esta segmentação'}</button>{editing&&<button type="button" className={secondaryClass} onClick={()=>setEditing(null)}>Novo rascunho</button>}</div></form>{error&&<p role="alert" className="mt-3 text-red-700">{error}</p>}{ok&&<p role="status" className="mt-3 text-green-700">{ok}</p>}<div className="mt-6 space-y-3">{items.map(x=><div key={x.id} className="rounded-xl border border-gray-200 p-4"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-semibold text-gray-900">{x.titulo}</p><p className="text-sm text-gray-500">{x.canal} · Rascunho</p></div><button className={secondaryClass} onClick={()=>setEditing(x)}>Editar rascunho</button></div><p className="mt-2 text-xs text-gray-500">Segmentação: {Object.entries(x.segmento).filter(([k,v])=>k!=='offset'&&v!==''&&v!==false).map(([k,v])=>`${k}: ${String(v)}`).join(' · ')||'Todos os cadastros acessíveis ao responsável'}</p></div>)}</div></section>;
}
