'use client';
import {useCallback,useEffect,useState,type FormEvent} from 'react';
import {gestao,mensagem,dinheiro,dataBR,hoje} from '../../lib/gestao/client';
import {formas,type Detalhe,type Cobranca} from '../../lib/gestao/types';
import {Field,Select,TextArea,buttonClass,secondaryClass,panelClass,Badge} from './Shared';
export default function ContratoDetalhe({id,onClose,onPaid}:{id:string;onClose:()=>void;onPaid:()=>void}){
 const [detail,setDetail]=useState<Detalhe|null>(null),[invoice,setInvoice]=useState<Cobranca|null>(null),[key,setKey]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[ok,setOk]=useState('');
 const load=useCallback(async()=>setDetail(await gestao<Detalhe>('contrato',{id})),[id]);
 useEffect(()=>{let live=true;gestao<Detalhe>('contrato',{id}).then(r=>{if(live)setDetail(r);}).catch(e=>{if(live)setError(mensagem(e));});return()=>{live=false;};},[id]);
 async function pay(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy||!invoice)return;setBusy(true);setError('');setOk('');try{const fd=new FormData(e.currentTarget);await gestao('pagamento',{...Object.fromEntries(fd),valor:Number(fd.get('valor')),cobranca_id:invoice.id,idempotency_key:key});setInvoice(null);setOk('Pagamento registrado.');await load();onPaid();}catch(e){setError(mensagem(e));}finally{setBusy(false);}}
 return <section className={panelClass}><div className="flex items-center justify-between gap-4"><h2 className="text-xl font-bold text-gray-900">Cobranças e histórico</h2><button className={secondaryClass} onClick={onClose}>Fechar</button></div>{error&&<p role="alert" className="mt-4 text-red-700">{error}</p>}{ok&&<p role="status" className="mt-4 text-green-700">{ok}</p>}{!detail?<p className="mt-4">Carregando…</p>:<><p className="mt-3 text-sm text-gray-500">{detail.contrato.servico} {detail.contrato.plano?`· ${detail.contrato.plano}`:''} · {dinheiro(detail.contrato.valor)}</p>
 {invoice&&<form key={invoice.id} onSubmit={pay} className="my-5 rounded-xl border border-red-200 bg-red-50/40 p-5"><h3 className="mb-3 font-bold text-gray-900">Registrar pagamento · vencimento {dataBR(invoice.vencimento)}</h3><fieldset disabled={busy} className="grid gap-4 md:grid-cols-3"><Field label="Valor recebido (R$) *" name="valor" type="number" step="0.01" min="0.01" max={invoice.saldo} required defaultValue={invoice.saldo}/><Field label="Data de pagamento *" name="data_pagamento" type="date" max={hoje()} required defaultValue={hoje()}/><Select label="Forma de pagamento" name="forma_pagamento" options={formas}/><div className="md:col-span-3"><TextArea label="Observações/comprovante" name="observacoes"/></div></fieldset><div className="mt-4 flex gap-3"><button disabled={busy} className={buttonClass}>{busy?'Registrando…':'Confirmar pagamento manual'}</button><button disabled={busy} type="button" className={secondaryClass} onClick={()=>setInvoice(null)}>Cancelar</button></div></form>}
 <div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-gray-200 text-gray-500">{['Competência','Vencimento','Valor','Recebido','Saldo','Status',''].map((x,i)=><th key={i} className="px-3 py-3 font-semibold">{x}</th>)}</tr></thead><tbody>{detail.cobrancas.map(b=><tr key={b.id} className="border-b border-gray-100"><td className="whitespace-nowrap px-3 py-3">{b.competencia.slice(0,7).split('-').reverse().join('/')}</td><td className="whitespace-nowrap px-3 py-3">{dataBR(b.vencimento)}</td><td className="whitespace-nowrap px-3 py-3">{dinheiro(b.valor)}</td><td className="whitespace-nowrap px-3 py-3">{dinheiro(b.pago)}</td><td className="whitespace-nowrap px-3 py-3">{dinheiro(b.saldo)}</td><td className="px-3 py-3"><Badge>{b.status}</Badge></td><td className="px-3 py-3">{b.saldo>0&&<button disabled={busy} className={secondaryClass} onClick={()=>{setInvoice(b);setKey(crypto.randomUUID());setError('');setOk('');}}>Registrar pagamento</button>}</td></tr>)}</tbody></table></div><h3 className="mt-6 font-bold text-gray-900">Pagamentos registrados</h3>{!detail.pagamentos.length?<p className="mt-2 text-sm text-gray-500">Nenhum pagamento registrado.</p>:<ul className="mt-3 divide-y divide-gray-100">{detail.pagamentos.map(p=><li key={p.id} className="py-3 text-sm"><span className="font-semibold">{dinheiro(p.valor)}</span> · {dataBR(p.data_pagamento)} · {p.forma_pagamento}<p className="mt-1 text-gray-500">{p.observacoes||'Registro manual'}</p></li>)}</ul>}</>}
 </section>;
}
