'use client';
import Link from 'next/link';
import {useEffect,useState,type FormEvent} from 'react';
import {gestao,mensagem,hoje} from '../../lib/gestao/client';
import {servicos,formas,type Cliente,type Contrato,type Lista} from '../../lib/gestao/types';
import {Field,Select,TextArea,buttonClass,secondaryClass,panelClass} from './Shared';
export default function ContratoForm({contrato,clienteInicial,onSaved,onCancel}:{contrato:Contrato|null;clienteInicial?:string;onSaved:(k:Contrato)=>void;onCancel:()=>void}){
 const [clients,setClients]=useState<Cliente[]>([]),[selected,setSelected]=useState(contrato?.cliente_id??clienteInicial??''),[service,setService]=useState(contrato?.servico??'Auditoria'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[search,setSearch]=useState('');
 useEffect(()=>{let live=true;const id=contrato?.cliente_id??clienteInicial;Promise.all([gestao<Lista<Cliente>>('clientes'),id?gestao<Cliente>('cliente',{id}):Promise.resolve(null)]).then(([r,c])=>{if(live)setClients(c?[c,...r.items.filter(x=>x.id!==c.id)]:r.items);}).catch(e=>{if(live)setError(mensagem(e));});return()=>{live=false;};},[contrato?.cliente_id,clienteInicial]);
 async function lookup(){setError('');try{const r=await gestao<Lista<Cliente>>('clientes',{busca:search});setClients(r.items);setSelected('');}catch(e){setError(mensagem(e));}}
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;setBusy(true);setError('');const fd=new FormData(e.currentTarget);try{const values=Object.fromEntries(fd);const k=await gestao<Contrato>('contrato_salvar',{...values,id:contrato?.id,updated_at:contrato?.updated_at,cliente_id:contrato?.cliente_id??selected,servico:service,data_inicio:contrato?.data_inicio??values.data_inicio,vencimento:contrato?.vencimento??values.vencimento,dia_vencimento:service==='RBK Digital'?(contrato?.dia_vencimento??Number(values.dia_vencimento)):null,valor:Number(values.valor)});onSaved(k);}catch(e){setError(mensagem(e));}finally{setBusy(false);}}
 return <section className={panelClass}><h2 className="mb-4 text-xl font-bold text-gray-900">{contrato?'Editar contratação':'Nova contratação'}</h2>{!contrato&&<div className="mb-5 rounded-xl bg-gray-50 p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-end"><div className="flex-1"><Field label="Localizar cliente no CRM por nome ou CNPJ" value={search} onChange={e=>setSearch(e.target.value)}/></div><button className={secondaryClass} onClick={()=>void lookup()}>Buscar cliente</button></div><p className="mt-2 text-xs text-gray-500">São exibidos até 100 resultados. Refine a busca para localizar outros cadastros. <Link href="/crm" className="font-bold text-red-700">Cadastrar no CRM →</Link></p></div>}
 <form onSubmit={save}><fieldset disabled={busy} className="grid gap-4 md:grid-cols-2 lg:grid-cols-3"><Select label="Cliente/farmácia *" name="cliente_id" required disabled={!!contrato} value={selected} onChange={setSelected} options={[{value:'',label:'Selecione o cliente'},...clients.map(c=>({value:c.id,label:`${c.razao_social} · ${c.cnpj??'Sem CNPJ'}`}))]}/><Select label="Serviço *" name="servico" options={servicos} value={service} onChange={setService} disabled={!!contrato}/><Field label={service==='RBK Digital'?'Valor mensal (R$) *':'Valor contratado (R$) *'} name="valor" type="number" step="0.01" min="0.01" max="999999999999.99" required defaultValue={contrato?.valor}/>
 <Select label="Forma de pagamento" name="forma_pagamento" options={formas} defaultValue={contrato?.forma_pagamento??'Pix'}/><Field label="Data de contratação *" name="data_contratacao" type="date" required defaultValue={contrato?.data_contratacao??hoje()}/><Field label="Data de início *" name="data_inicio" type="date" min="2000-01-01" required readOnly={!!contrato} defaultValue={contrato?.data_inicio??hoje()}/><Field label="Primeiro vencimento *" name="vencimento" type="date" required readOnly={!!contrato} defaultValue={contrato?.vencimento??hoje()}/>
 {service==='RBK Digital'&&<><Field label="Plano *" name="plano" required maxLength={200} defaultValue={contrato?.plano}/><Field label="Dia de vencimento mensal *" name="dia_vencimento" type="number" required min={1} max={31} readOnly={!!contrato} defaultValue={contrato?.dia_vencimento??Number(hoje().slice(-2))}/></>}
 <Select label={service==='RBK Digital'?'Status da assinatura':'Status do contrato'} name="status" options={[{value:'ativo',label:'Ativo'},{value:'suspenso',label:'Suspenso'},{value:'cancelado',label:'Cancelado'}]} defaultValue={contrato?.status??'ativo'}/><div className="md:col-span-2 lg:col-span-3"><TextArea label="Observações" name="observacoes" value={contrato?.observacoes}/></div></fieldset><p className="mt-4 text-sm text-gray-500">{contrato?'Alterações de valor afetam apenas mensalidades ainda não geradas. O calendário e o cliente são preservados. Cancelar mantém o histórico e os débitos vencidos.':'Mensalidades são lançamentos internos. Nenhum boleto, Pix ou débito será enviado. Dias 29, 30 e 31 são ajustados ao último dia de meses mais curtos.'}</p>{error&&<p role="alert" className="mt-4 text-red-700">{error}</p>}<div className="mt-5 flex gap-3"><button disabled={busy} className={buttonClass}>{busy?'Salvando…':'Salvar contratação'}</button><button type="button" disabled={busy} onClick={onCancel} className={secondaryClass}>Cancelar</button></div></form></section>;
}
