'use client';
import Link from 'next/link';
import {useCallback,useEffect,useRef,useState,type FormEvent} from 'react';
import {gestao,mensagem,dataBR} from '../../lib/gestao/client';
import {statusCRM,interesses,estados,type Cliente,type Contexto,type Lista} from '../../lib/gestao/types';
import {Field,Select,buttonClass,secondaryClass,panelClass,Pager,Badge} from './Shared';
import ClienteForm from './ClienteForm';
import Comunicados from './Comunicados';
export default function CRM({ctx}:{ctx:Contexto}){
 const [list,setList]=useState<Lista<Cliente>>({items:[],total:0}),[filters,setFilters]=useState<Record<string,unknown>>({}),[offset,setOffset]=useState(0),[busy,setBusy]=useState(true),[error,setError]=useState(''),[ok,setOk]=useState(''),[editing,setEditing]=useState<Cliente|null|undefined>(undefined),[tab,setTab]=useState('cadastros');const seq=useRef(0);
 const load=useCallback(async()=>{const request=++seq.current;try{const r=await gestao<Lista<Cliente>>('clientes',{...filters,offset});if(request===seq.current){setList(r);setError('');}}catch(e){if(request===seq.current)setError(mensagem(e));}finally{if(request===seq.current)setBusy(false);}},[filters,offset]);
 useEffect(()=>{const request=++seq.current;void gestao<Lista<Cliente>>('clientes',{...filters,offset}).then(r=>{if(request===seq.current){setList(r);setError('');}}).catch(e=>{if(request===seq.current)setError(mensagem(e));}).finally(()=>{if(request===seq.current)setBusy(false);});return()=>{seq.current=request+1;};},[filters,offset]);
 function filter(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);setFilters({...Object.fromEntries(fd),aguardando:fd.has('aguardando')});setOffset(0);}
 async function convert(c:Cliente){if(busy)return;setBusy(true);setError('');try{await gestao('cliente_salvar',{...c,status:'Cliente'});setOk('Lead convertido em cliente. O cadastro e seus vínculos foram preservados.');await load();}catch(e){setError(mensagem(e));}finally{setBusy(false);}}
 return <div className="space-y-6"><div className="flex flex-wrap justify-between gap-3"><div className="flex gap-2"><button className={tab==='cadastros'?buttonClass:secondaryClass} onClick={()=>setTab('cadastros')}>Leads e clientes</button><button className={tab==='comunicados'?buttonClass:secondaryClass} onClick={()=>setTab('comunicados')}>Comunicados</button></div><button className={buttonClass} onClick={()=>{setEditing(null);setTab('cadastros');setOk('');}}>+ Novo cadastro</button></div>
 {editing!==undefined&&tab==='cadastros'&&<ClienteForm key={editing?.id??'new'} cliente={editing} ctx={ctx} onCancel={()=>setEditing(undefined)} onSaved={()=>{setEditing(undefined);setOk('Cadastro salvo.');void load();}}/>}
 <section className={panelClass}><h2 className="mb-4 text-lg font-bold text-gray-900">Filtrar e segmentar</h2><form onSubmit={filter}><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Field label="Razão social ou CNPJ" name="busca"/><Select label="Status" name="status" options={[{value:'',label:'Todos'},...statusCRM]}/><Select label="Interesse" name="interesse" options={[{value:'',label:'Todos'},...interesses]}/><Select label="UF" name="uf" options={[{value:'',label:'Todas'},...estados]}/><Field label="Cidade" name="cidade"/><Select label="Responsável" name="responsavel_id" options={[{value:'',label:'Todos da minha carteira'},...ctx.responsaveis.map(x=>({value:x.id,label:x.nome}))]}/><label className="flex items-center gap-2 text-sm text-gray-700"><input type="checkbox" name="aguardando" className="accent-red-700"/>Aguardando credenciamento/oportunidade</label><div className="flex items-end"><button disabled={busy} className={buttonClass}>Aplicar filtros</button></div></div></form></section>
 {error&&<p role="alert" className="text-red-700">{error}</p>}{ok&&<p role="status" className="text-green-700">{ok}</p>}{busy&&<p role="status" className="text-sm text-gray-500">Carregando cadastros…</p>}
 {tab==='comunicados'?<Comunicados segmento={filters} total={list.total}/>:<section className={panelClass}><h2 className="mb-4 text-xl font-bold text-gray-900">Leads e clientes <span className="text-base font-normal text-gray-500">({list.total})</span></h2>{!busy&&!list.items.length&&<p className="py-8 text-center text-gray-500">Nenhum cadastro encontrado. Adicione um lead ou ajuste os filtros.</p>}<div className="grid gap-4 lg:grid-cols-2">{list.items.map(c=><article key={c.id} className="rounded-2xl border border-gray-200 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-bold text-gray-900">{c.razao_social}</h3><p className="mt-1 text-sm text-gray-500">{c.cnpj??'CNPJ ainda não informado'} · {[c.cidade,c.uf].filter(Boolean).join('/')||'Localidade não informada'}</p></div><Badge>{c.status}</Badge></div><p className="mt-3 text-sm text-gray-700">{c.interesses.join(' · ')||'Interesses não informados'}</p><p className="mt-2 break-words text-sm text-gray-500">{[c.contato,c.whatsapp,c.email].filter(Boolean).join(' · ')||'Contato não informado'}</p><p className="mt-2 text-sm text-gray-500">Último contato: {dataBR(c.ultimo_contato)} · Próxima ação: {c.proxima_acao||'—'} {c.proxima_acao_data?`(${dataBR(c.proxima_acao_data)})`:''}</p>{c.aguardando_credenciamento&&<p className="mt-2 text-sm font-semibold text-red-700">Aguardando credenciamento/oportunidade</p>}{c.farm_id&&<p className="mt-2 text-xs text-gray-500">Vinculado ao cadastro existente de farmácia</p>}<div className="mt-4 flex flex-wrap gap-2"><button className={secondaryClass} onClick={()=>{setEditing(c);window.scrollTo({top:0,behavior:'smooth'});}}>Editar</button>{c.status!=='Cliente'&&<button disabled={busy} className={secondaryClass} onClick={()=>void convert(c)}>Converter em cliente</button>}<Link className={secondaryClass} href={`/financeiro?cliente=${c.id}`}>Criar contratação</Link></div></article>)}</div><Pager total={list.total} offset={offset} onChange={setOffset}/></section>}
 </div>;
}
