'use client';
import {useCallback,useEffect,useRef,useState,type FormEvent} from 'react';
import {gestao,mensagem,dinheiro,dataBR} from '../../lib/gestao/client';
import {servicos,type Contrato,type Financeiro as Report} from '../../lib/gestao/types';
import {Field,Select,buttonClass,secondaryClass,panelClass,Pager,Badge} from './Shared';
import ContratoForm from './ContratoForm';
import ContratoDetalhe from './ContratoDetalhe';
function clienteURL(){if(typeof window==='undefined')return undefined;const id=new URL(window.location.href).searchParams.get('cliente');return id&&/^[0-9a-f-]{36}$/i.test(id)?id:undefined;}
export default function Financeiro(){
 const [report,setReport]=useState<Report|null>(null),[filters,setFilters]=useState<Record<string,unknown>>({}),[offset,setOffset]=useState(0),[busy,setBusy]=useState(true),[error,setError]=useState(''),[ok,setOk]=useState(''),[editing,setEditing]=useState<Contrato|null|undefined>(()=>clienteURL()?null:undefined),[cliente,setCliente]=useState<string|undefined>(clienteURL),[detail,setDetail]=useState<string|null>(null);const seq=useRef(0);
 const load=useCallback(async(sync=false)=>{const request=++seq.current;try{if(sync)await gestao('sincronizar');const r=await gestao<Report>('financeiro',{...filters,offset});if(request===seq.current){setReport(r);setError('');}}catch(e){if(request===seq.current)setError(mensagem(e));}finally{if(request===seq.current)setBusy(false);}},[filters,offset]);
 useEffect(()=>{const request=++seq.current;void gestao('sincronizar').then(()=>gestao<Report>('financeiro',{...filters,offset})).then(r=>{if(request===seq.current){setReport(r);setError('');}}).catch(e=>{if(request===seq.current)setError(mensagem(e));}).finally(()=>{if(request===seq.current)setBusy(false);});return()=>{seq.current=request+1;};},[filters,offset]);
 function filter(e:FormEvent<HTMLFormElement>){e.preventDefault();setFilters(Object.fromEntries(new FormData(e.currentTarget)));setOffset(0);}
 const metrics=report?[['MRR RBK Digital',dinheiro(report.indicadores.mrr)],['Recebido no mês',dinheiro(report.indicadores.recebido_mes)],['A receber',dinheiro(report.indicadores.a_receber)],['Em atraso',dinheiro(report.indicadores.atrasados)],['Assinaturas ativas',String(report.indicadores.assinaturas_ativas)]]:[];
 return <div className="space-y-6"><div className="flex flex-wrap justify-between gap-3"><p className="text-sm text-gray-500">Contratos e mensalidades da sua carteira</p><div className="flex flex-wrap gap-2"><button className={secondaryClass} disabled={busy} onClick={()=>void load(true)}>Atualizar mensalidades</button><button className={buttonClass} onClick={()=>{setEditing(null);setCliente(undefined);setDetail(null);setOk('');}}>+ Nova contratação</button></div></div>
 {error&&<p role="alert" className="text-red-700">{error}</p>}{ok&&<p role="status" className="text-green-700">{ok}</p>}{busy&&<p role="status" className="text-sm text-gray-500">Atualizando financeiro…</p>}
 <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{metrics.map(([label,value])=><div key={label} className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><p className="text-xs font-semibold uppercase tracking-wide text-gray-500">{label}</p><p className="mt-3 break-words text-2xl font-bold text-gray-900">{value}</p></div>)}</div><p className="text-xs text-gray-500">MRR considera assinaturas ativas já iniciadas. A receber inclui atrasados. Mensalidades são geradas até o mês atual, além do primeiro vencimento contratado.</p>
 {editing!==undefined&&<ContratoForm key={editing?.id??`new-${cliente??''}`} contrato={editing} clienteInicial={cliente} onCancel={()=>setEditing(undefined)} onSaved={()=>{setEditing(undefined);setOk('Contratação salva.');void load();}}/>}
 {detail&&<ContratoDetalhe key={detail} id={detail} onClose={()=>setDetail(null)} onPaid={()=>void load()}/>}
 <section className={panelClass}><h2 className="mb-4 text-xl font-bold text-gray-900">Contratações</h2><form onSubmit={filter} className="mb-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Field label="Cliente ou CNPJ" name="busca"/><Select label="Serviço" name="servico" options={[{value:'',label:'Todos'},...servicos]}/><Select label="Situação de pagamento" name="status" options={[{value:'',label:'Todas'},{value:'pago',label:'Pago'},{value:'pendente',label:'Pendente'},{value:'atrasado',label:'Atrasado'},{value:'cancelado',label:'Cancelado'}]}/><div className="flex items-end"><button className={buttonClass} disabled={busy}>Aplicar filtros</button></div></form>
 {!busy&&!report?.items.length&&<p className="py-8 text-center text-gray-500">Nenhuma contratação encontrada. Cadastre o cliente no CRM e registre o serviço contratado.</p>}
 <div className="space-y-4">{report?.items.map(k=><article key={k.id} className="rounded-2xl border border-gray-200 p-5"><div className="flex flex-col justify-between gap-4 md:flex-row"><div><h3 className="font-bold text-gray-900">{k.razao_social}</h3><p className="mt-1 text-sm text-gray-500">{k.cnpj} · {k.servico}{k.plano?` · ${k.plano}`:''}</p><p className="mt-3 font-bold text-gray-900">{dinheiro(k.valor)}{k.servico==='RBK Digital'?' / mês':''}</p><p className="mt-2 text-sm text-gray-500">{k.forma_pagamento} · Contrato {k.status} · Próxima cobrança em aberto: {dataBR(k.proxima_cobranca)}</p></div><div className="flex flex-wrap items-center gap-2"><Badge>{k.pagamento_status}</Badge><button className={secondaryClass} onClick={()=>{setDetail(k.id);setEditing(undefined);window.scrollTo({top:0,behavior:'smooth'});}}>Cobranças e pagamentos</button><button className={secondaryClass} onClick={()=>{setEditing(k);setDetail(null);window.scrollTo({top:0,behavior:'smooth'});}}>Editar contrato</button></div></div></article>)}</div><Pager total={report?.total??0} offset={offset} onChange={setOffset}/></section>
 <section className="rounded-2xl border border-dashed border-gray-300 p-5"><h2 className="font-bold text-gray-900">Integração de cobrança</h2><p className="mt-2 text-sm text-gray-500">Pix Automático, boleto/Pix e cartão recorrente aguardam configuração de um gateway. Nesta etapa, registre os pagamentos manualmente. Nenhuma cobrança externa é emitida.</p></section>
 </div>;
}
