'use client';
import {numero,dataBr} from '../../lib/vendas/domain';
import type {ProdutoCompra} from '../../lib/compras/domain';
export function Barras({produtos,campo,unidade}:{produtos:ProdutoCompra[];campo:'consumo'|'cobertura'|'sugestao'|'projecao30'|'projecao60'|'projecao90';unidade:string}){
 const rows=produtos.filter(r=>r[campo]!==null).sort((a,b)=>campo==='cobertura'?a.cobertura!-b.cobertura!:b[campo]!-a[campo]!).slice(0,8),max=Math.max(1,...rows.map(r=>r[campo]!));
 if(!rows.length)return <Vazio>Sem dados suficientes para este gráfico.</Vazio>;
 return <div className="space-y-4">{rows.map(r=><div key={r.chave}><div className="mb-1 flex justify-between gap-4 text-sm"><span className="min-w-0 break-words">{r.produto}</span><strong className="shrink-0">{numero(r[campo])} {campo==='cobertura'?'dias':unidade}</strong></div><div className="h-2 rounded-full bg-gray-100"><div className={`h-2 rounded-full ${r.alerta==='ruptura'?'bg-red-600':r.alerta==='baixo'?'bg-amber-500':'bg-red-800'}`} style={{width:`${Math.max(0,r[campo]!/max*100)}%`}}/></div>{r.parcial&&<small className="text-amber-800">Quantidade conhecida · base parcial</small>}</div>)}<p className="text-xs text-gray-500">Até 8 produtos, separados por unidade.</p></div>;
}
export function Vazio({children}:{children:React.ReactNode}){return <div className="flex min-h-40 items-center justify-center rounded-xl border border-dashed border-gray-200 p-6 text-center text-sm text-gray-500">{children}</div>;}
export function EvolucaoCompras({pontos,unidade}:{pontos:{data:string;valor:number|null;parcial:boolean}[];unidade:string}){
 const max=Math.max(1,...pontos.map(p=>p.valor??0)),w=Math.max(650,pontos.length*22);
 if(!pontos.some(p=>p.valor!==null))return <Vazio>Sem consumo confirmado para esta unidade.</Vazio>;
 return <><div className="overflow-x-auto" tabIndex={0} aria-label="Evolução do consumo"><svg role="img" aria-label={`Consumo por período em ${unidade}`} viewBox={`0 0 ${w} 230`} className="h-[230px] w-full" style={{minWidth:w}}>{[0,.5,1].map(f=><g key={f}><line x1="55" y1={190-160*f} x2={w-10} y2={190-160*f} stroke="#e5e7eb"/><text x="48" y={194-160*f} textAnchor="end" fontSize="10" fill="#6b7280">{numero(max*f)}</text></g>)}{pontos.map((p,i)=>{const slot=(w-75)/pontos.length,x=60+slot*i,h=(p.valor??0)/max*160;return <g key={p.data}><title>{p.data}: {p.valor===null?'Sem informação':numero(p.valor)} {unidade}{p.parcial?' (parcial)':''}</title>{p.valor===null?<text x={x+slot/2} y="187" textAnchor="middle" fill="#9ca3af">—</text>:<rect x={x} y={190-h} width={Math.max(2,slot-4)} height={h} fill={p.parcial?'#f59e0b':'#b91c1c'} rx="2"/>}{i%Math.ceil(pontos.length/18)===0&&<text x={x} y="214" fontSize="10" fill="#6b7280">{p.data.length===7?p.data.slice(5):dataBr(p.data).slice(0,5)}</text>}</g>;})}</svg></div><details className="mt-3 text-xs text-gray-600"><summary className="cursor-pointer">Ver valores da evolução</summary><div className="mt-2 max-h-48 overflow-auto">{pontos.map(p=><p key={p.data}>{p.data}: {numero(p.valor)} {unidade}{p.parcial?' · parcial':''}</p>)}</div></details><p className="mt-2 text-xs text-gray-500">Data da autorização. Traço indica ausência de informação, não consumo zero.</p></>;
}
