'use client';
import {useRef,useState} from 'react';
import {lerArquivo,mapearEstoque,type AbaEstoque,type MapaEstoque} from '../../lib/compras/importar';
import type {EstoqueItem} from '../../lib/compras/domain';
import {numero,periodo} from '../../lib/vendas/domain';
const initial:MapaEstoque={ean:-1,produto:-1,quantidade:-1,unidade:-1};
export default function ImportarEstoque({onSave,onClose,anterior}:{onSave:(data:string,arquivo:string,itens:EstoqueItem[])=>Promise<void>;onClose:()=>void;anterior:boolean}){
 const [abas,setAbas]=useState<AbaEstoque[]>([]),[aba,setAba]=useState(0),[nome,setNome]=useState(''),[mapa,setMapa]=useState(initial),[fixa,setFixa]=useState(''),[data,setData]=useState(()=>periodo('hoje').fim),[erro,setErro]=useState(''),[busy,setBusy]=useState(false),[cab,setCab]=useState(0),[numeros,setNumeros]=useState<'br'|'decimal'|'auto'>('br');
 const generation=useRef(0);
 const rows=abas[aba]?.linhas||[],headers=rows[cab]||[];
 let preview:ReturnType<typeof mapearEstoque>|null=null;let mapError='';
 try{if(rows.length)preview=mapearEstoque(rows.slice(cab+1),mapa,fixa,numeros);}catch(e){mapError=e instanceof Error?e.message:'Mapeamento inválido';}
 function sugerir(h:string[]){const idx=(rx:RegExp)=>h.findIndex(x=>rx.test(x.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()));setMapa({ean:idx(/ean|gtin|barras/),produto:idx(/produto|descricao|nome/),quantidade:idx(/estoque|saldo|quantidade/),unidade:idx(/unidade|^un$|^und$/)});}
 async function arquivo(f:File|undefined){if(!f)return;const id=++generation.current;setBusy(true);setErro('');setAbas([]);try{const a=await lerArquivo(f);if(id!==generation.current)return;setAbas(a);setAba(0);setCab(0);setNome(f.name);setNumeros(/\.csv$/i.test(f.name)?'br':'auto');sugerir(a[0]?.linhas[0]||[]);}catch(e){if(id===generation.current)setErro(e instanceof Error?e.message:'Falha na leitura.');}finally{if(id===generation.current)setBusy(false);}}
 async function save(){if(!preview||preview.erros.length||!preview.itens.length||busy)return;setBusy(true);setErro('');try{await onSave(data,nome,preview.itens);onClose();}catch(e){setErro(e instanceof Error?e.message:'Falha ao salvar.');}finally{setBusy(false);}}
 return <section className="rbk-card my-6 p-5 md:p-7" aria-label="Importação de estoque"><div className="flex items-center justify-between gap-3"><h2 className="text-xl font-bold">Importar estoque</h2><button type="button" disabled={busy} onClick={onClose} className="rbk-secondary min-h-11 rounded-xl px-4 py-2 text-sm font-semibold disabled:opacity-40">Fechar</button></div><p className="mt-2 text-sm text-gray-600">Selecione a planilha, confira as colunas e revise a prévia. Até 5 MB e 20 mil produtos. EAN/GTIN como texto; informe a mesma unidade usada nas dispensações.</p>
 <div className="mt-5 grid gap-4 md:grid-cols-3"><label className="text-sm font-semibold">Arquivo XLSX ou CSV<input type="file" accept=".xlsx,.csv" disabled={busy} onChange={e=>void arquivo(e.target.files?.[0])} className="mt-2 block w-full text-sm"/></label><label className="text-sm font-semibold">Data da posição de estoque<input type="date" value={data} min="2000-01-01" max={periodo('hoje').fim} onChange={e=>setData(e.target.value)} disabled={busy} className="rbk-input mt-2 w-full"/></label>{abas.length>0&&<label className="text-sm font-semibold">Aba<select className="rbk-input mt-2 w-full" disabled={busy} value={aba} onChange={e=>{const n=Number(e.target.value);setAba(n);setCab(0);sugerir(abas[n].linhas[0]||[]);}}>{abas.map((a,i)=><option key={i} value={i}>{a.nome}</option>)}</select></label>}</div>
 {rows.length>0&&<><label className="mt-4 block text-sm font-semibold">Linha do cabeçalho<select className="rbk-input ml-3" value={cab} disabled={busy} onChange={e=>{const n=Number(e.target.value);setCab(n);sugerir(rows[n]);}}>{rows.slice(0,20).map((_,i)=><option key={i} value={i}>{i+1}</option>)}</select></label><div className="mt-4 grid gap-3 md:grid-cols-4">{([['ean','EAN / GTIN'],['produto','Produto'],['quantidade','Estoque atual'],['unidade','Unidade']] as const).map(([k,label])=><label key={k} className="text-sm font-semibold">{label}<select className="rbk-input mt-2 w-full" value={mapa[k]} disabled={busy} onChange={e=>setMapa({...mapa,[k]:Number(e.target.value)})}><option value={-1}>{k==='unidade'?'Usar unidade fixa':'Selecionar coluna'}</option>{headers.map((h,i)=><option key={i} value={i}>{i+1}. {h||'Sem título'}</option>)}</select></label>)}</div>{mapa.unidade<0&&<label className="mt-4 block text-sm font-semibold">Unidade de todos os produtos<input className="rbk-input ml-3" placeholder="Ex.: CX ou UN" maxLength={30} value={fixa} disabled={busy} onChange={e=>setFixa(e.target.value)}/></label>}
 <label className="mt-4 block text-sm font-semibold">Formato das quantidades<select className="rbk-input ml-3" disabled={busy} value={numeros} onChange={e=>setNumeros(e.target.value as 'br'|'decimal'|'auto')}><option value="br">Brasileiro: 1.234,5 = 1234,5</option><option value="decimal">Decimal com ponto: 1234.5 = 1234,5</option><option value="auto">XLSX numérico / texto com vírgula</option></select></label>{mapError&&<p className="mt-4 text-sm text-amber-800">{mapError}</p>}
 {preview&&<div className="mt-5"><p className="font-semibold">{preview.itens.length} produtos válidos · {preview.erros.length} erros · {preview.semEAN} sem EAN</p>{preview.semEAN>0&&<p className="mt-2 text-sm text-amber-800">Itens sem EAN serão preservados, mas não serão associados ao consumo pelo nome.</p>}{preview.erros.length>0&&<div role="alert" className="mt-3 max-h-40 overflow-auto rounded-xl bg-red-50 p-4 text-sm text-red-800">{preview.erros.slice(0,100).map((e,i)=><p key={i}>{e.replace(/^Linha (\d+)/,(_,n)=>`Linha ${Number(n)+cab}`)}</p>)}{preview.erros.length>100&&<p>Há mais erros. Corrija a planilha e tente novamente.</p>}</div>}<div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><caption className="mb-2 text-left text-gray-500">Prévia dos primeiros 8 produtos válidos</caption><thead><tr>{['EAN/GTIN','Produto','Unidade','Estoque'].map(h=><th className="p-2" key={h}>{h}</th>)}</tr></thead><tbody>{preview.itens.slice(0,8).map((i,n)=><tr className="border-t border-gray-100" key={n}><td className="p-2">{i.ean||'Sem EAN'}</td><td className="p-2">{i.produto}</td><td className="p-2">{i.unidade}</td><td className="p-2">{numero(i.quantidade)}</td></tr>)}</tbody></table></div>
 <p className="mt-4 rounded-xl bg-amber-50 p-3 text-sm text-amber-900">{anterior?'Esta importação substituirá integralmente a posição anterior. Produtos ausentes nesta planilha ficarão sem estoque informado.':'Esta será a posição inicial do estoque da farmácia.'} Confira a data e as unidades antes de salvar.</p><button type="button" onClick={()=>void save()} disabled={busy||!data||!preview.itens.length||!!preview.erros.length} className="rbk-primary min-h-11 rounded-xl px-4 py-2 text-sm font-bold disabled:opacity-40 mt-4">{busy?'Processando…':`Confirmar importação de ${preview.itens.length} produtos`}</button></div>}</>}
 {erro&&<p role="alert" className="mt-4 rounded-xl bg-red-50 p-4 text-sm text-red-800">{erro}</p>}
 </section>;
}
