'use client';
import {useState} from 'react';
import {numero} from '../../lib/vendas/domain';
import type {ProdutoCompra} from '../../lib/compras/domain';
export const statusLabel={ruptura:'Risco de ruptura',baixo:'Baixo estoque',adequado:'Cobertura adequada',indisponivel:'Sem cálculo de cobertura'};
export default function TabelaCompras({produtos,horizonte}:{produtos:ProdutoCompra[];horizonte:30|60|90}){
 const [busca,setBusca]=useState(''),[pagina,setPagina]=useState(0);
 const normal=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
 const rows=produtos.filter(p=>normal(`${p.produto} ${p.ean||''} ${p.principio}`).includes(normal(busca)));
 const pages=Math.max(1,Math.ceil(rows.length/25)),pg=Math.min(pagina,pages-1);
 const fmt=(n:number|null)=>n===null?'—':numero(n);
 return <section className="rbk-card mt-6 min-w-0 p-5 md:p-7"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-lg font-bold">Planejamento por produto</h2><p className="mt-1 text-sm text-gray-500">{rows.length} produtos · exportação inclui todos os produtos do período</p></div><label className="text-sm">Buscar produto, EAN ou princípio ativo<input className="rbk-input mt-1 block w-full" value={busca} onChange={e=>{setBusca(e.target.value);setPagina(0);}}/></label></div>
 <div className="mt-5 overflow-x-auto" tabIndex={0} aria-label="Tabela de planejamento por produto"><table className="w-full min-w-[1350px] text-left text-sm"><thead className="bg-gray-50 text-xs text-gray-600"><tr>{['EAN/GTIN','Produto / princípio ativo','Unidade','Estoque atual','Consumo no período','Média diária','Cobertura (dias)','Projeção 30 / 60 / 90d',`Comprar (${horizonte}d)`,'Situação'].map(h=><th key={h} className="px-3 py-4">{h}</th>)}</tr></thead><tbody>{rows.slice(pg*25,(pg+1)*25).map(p=><tr key={p.chave} className="border-b border-gray-100 align-top"><td className="px-3 py-4 font-mono text-xs">{p.ean||'Sem EAN'}</td><td className="max-w-64 px-3 py-4"><span className="font-semibold">{p.produto}</span><small className="mt-1 block text-gray-500">{p.principio}</small></td><td className="px-3 py-4">{p.unidade||'Não informada'}</td><td className="px-3 py-4">{fmt(p.estoque)}</td><td className="px-3 py-4">{fmt(p.consumo)}{p.parcial&&<small className="block text-amber-700">Base parcial</small>}</td><td className="px-3 py-4">{fmt(p.diaria)}</td><td className="px-3 py-4">{fmt(p.cobertura)}</td><td className="px-3 py-4">{[p.projecao30,p.projecao60,p.projecao90].map(fmt).join(' / ')}</td><td className="px-3 py-4 font-bold">{fmt(p.sugestao)}</td><td className="max-w-56 px-3 py-4"><span className={`inline-block rounded-full px-2 py-1 text-xs font-semibold ${p.alerta==='ruptura'?'bg-red-100 text-red-800':p.alerta==='baixo'?'bg-amber-100 text-amber-800':p.alerta==='adequado'?'bg-green-50 text-green-800':'bg-gray-100 text-gray-600'}`}>{statusLabel[p.alerta]}</span><small className={`mt-2 block ${p.correspondencia.includes('Sem')?'text-amber-800':'text-gray-500'}`}>{p.correspondencia}</small></td></tr>)}</tbody></table>{!rows.length&&<p className="p-8 text-center text-sm text-gray-500">Nenhum produto disponível para este filtro.</p>}</div>
 <div className="mt-4 flex items-center justify-between gap-4 text-sm"><span>Página {pg+1} de {pages}</span><div className="flex gap-2"><button className="rbk-secondary min-h-11 rounded-xl px-4 py-2 text-sm font-semibold disabled:opacity-40" disabled={pg===0} onClick={()=>setPagina(pg-1)}>Anterior</button><button className="rbk-secondary min-h-11 rounded-xl px-4 py-2 text-sm font-semibold disabled:opacity-40" disabled={pg>=pages-1} onClick={()=>setPagina(pg+1)}>Próxima</button></div></div><p className="mt-3 text-xs text-gray-500">— indica informação indisponível. Estoque sem consumo confirmado não equivale a consumo zero. A quantidade sugerida considera somente as dispensações visíveis no RBK.</p></section>;
}
