'use client';
import DemandaFutura from '../proximas/DemandaFutura';
import {useLayoutEffect} from 'react';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {createClient} from '../../lib/supabase/client';
import {carregarVendas,type DadosVendas} from '../../lib/vendas/consulta';
import {periodo,numero,dataBr,type ModoPeriodo,type Intervalo} from '../../lib/vendas/domain';
import {carregarEstoque,salvarEstoque,type ContextoEstoque} from '../../lib/compras/consulta';
import {planejar,evolucaoConsumo,type EstoqueItem,type ProdutoCompra} from '../../lib/compras/domain';
import ImportarEstoque from '../../components/compras/ImportarEstoque';
import TabelaCompras from '../../components/compras/TabelaCompras';
import {Barras,EvolucaoCompras} from '../../components/compras/GraficosCompras';
const modos:[ModoPeriodo,string][]=[['hoje','Hoje'],['7dias','7 dias'],['mes','Mês'],['ano','Ano'],['personalizado','Período personalizado']];
const btn='min-h-11 rounded-xl px-4 py-2 text-sm font-semibold disabled:opacity-40';
const erroTexto=(e:unknown)=>e instanceof Error?e.message:'Não foi possível concluir. Tente novamente.';
type Resultado={dados:DadosVendas;estoque:ContextoEstoque;p:Intervalo};
export default function ComprasConteudo({farmId,onBusy}:{farmId:string;onBusy:(value:boolean)=>void}){
 const [resultado,setResultado]=useState<Resultado|null>(null),[busy,setBusy]=useState(false),[erro,setErro]=useState(''),[mensagem,setMensagem]=useState(''),[modo,setModo]=useState<ModoPeriodo>('mes'),[inicio,setInicio]=useState(''),[fim,setFim]=useState(''),[importando,setImportando]=useState(false),[formato,setFormato]=useState<'xlsx'|'csv'>('xlsx'),[horizonte,setHorizonte]=useState<30|60|90>(30),[risco,setRisco]=useState(7),[baixo,setBaixo]=useState(15),[un,setUn]=useState(''),[necessidade,setNecessidade]=useState<'projecao'|'compra'>('projecao');
 const request=useRef(0),locked=useRef(false);
 const buscar=useCallback(async(m:ModoPeriodo,i='',f='')=>{
 const id=++request.current;setBusy(true);setErro('');setResultado(null);setMensagem('');setImportando(false);
 try{const p=periodo(m,new Date(),i,f);if(p.fim>periodo('hoje').fim)throw new Error('Selecione um período encerrado até hoje.');
 const client=createClient();const [dados,estoque]=await Promise.all([carregarVendas(client,p,{farmId}),carregarEstoque(client,farmId)]);
 if(id===request.current){setResultado({dados,estoque,p});setUn('');}
 }catch(e){if(id===request.current)setErro(erroTexto(e));}finally{if(id===request.current)setBusy(false);}
 },[farmId]);
 useEffect(()=>{const ctrl=request;const timer=setTimeout(()=>void buscar('mes'),0);return()=>{clearTimeout(timer);ctrl.current++;};},[buscar]);
 const analise=useMemo(()=>resultado?planejar(resultado.dados.autorizacoes,resultado.dados.itens,resultado.estoque.base?.itens??null,resultado.p,horizonte,risco,baixo):null,[resultado,horizonte,risco,baixo]);
 const produtos=analise?.produtos||[];
 const unidades=[...new Set(produtos.map(p=>p.unidade))].sort();const atual=unidades.includes(un)?un:(unidades[0]??'');const selecionados=produtos.filter(p=>p.unidade===atual);
 const sum=(campo:keyof ProdutoCompra)=>{const nums=selecionados.map(p=>p[campo]).filter((n):n is number=>typeof n==='number');return nums.length?nums.reduce((a,b)=>a+b,0):null;};
 const quantidadeEstoque=sum('estoque'),media=sum('diaria');
 const pontos=resultado?evolucaoConsumo(resultado.dados.autorizacoes,resultado.dados.itens,resultado.p,atual):[];
 const alertaRuptura=produtos.filter(p=>p.alerta==='ruptura').length,alertaBaixo=produtos.filter(p=>p.alerta==='baixo').length;
 const semCorrespondencia=produtos.filter(p=>p.correspondencia.startsWith('Sem')||p.correspondencia==='Unidade não informada').length;
 function mudar(m:ModoPeriodo){if(locked.current)return;setModo(m);setErro('');setResultado(null);setImportando(false);if(m==='personalizado'){request.current++;setBusy(false);}else void buscar(m);}
 async function importar(data:string,arquivo:string,itens:EstoqueItem[]){if(!resultado)throw new Error('Atualize o painel.');locked.current=true;setBusy(true);try{const base=await salvarEstoque(createClient(),resultado.estoque,data,arquivo,itens);setResultado({...resultado,estoque:{...resultado.estoque,base}});setMensagem(`Estoque importado: ${itens.length} produtos.`);}finally{locked.current=false;setBusy(false);}}
 async function exportar(){if(!resultado||!analise||locked.current)return;locked.current=true;setBusy(true);setErro('');try{const {baixarCompras}=await import('../../lib/compras/exportar');await baixarCompras(produtos,resultado.p,horizonte,resultado.estoque.base,formato);setMensagem('Planilha preparada com todos os produtos do período.');}catch(e){setErro(erroTexto(e));}finally{locked.current=false;setBusy(false);}}
 const field=necessidade==='compra'?'sugestao':horizonte===30?'projecao30':horizonte===60?'projecao60':'projecao90';
 const cards=[['Estoque informado',numero(quantidadeEstoque),'Soma dos saldos importados nesta unidade'],['Consumo médio diário',numero(media),'Produtos com quantidade completa na base confirmada'],['Consumo médio mensal',numero(sum('mensal')),'Equivalente a 30 dias'],[`Reposição sugerida · ${horizonte} dias`,numero(sum('sugestao')),'Somente produtos com estoque e consumo compatíveis']];
 useLayoutEffect(()=>{onBusy(busy);return()=>onBusy(false);},[busy,onBusy]);
 return <div>
 <div className="rbk-container py-7 sm:py-9"><div className="mb-7 flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-red-600">Gestão • Programa Farmácia Popular</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-gray-900">Planejamento de Compras</h1><p className="mt-2 text-sm leading-6 text-gray-500">Acompanhar consumo e projetar necessidade de reposição</p></div><div className="flex flex-wrap gap-2"><button className={`rbk-secondary ${btn}`} disabled={busy||!resultado?.estoque.farmId||!resultado?.estoque.disponivel} onClick={()=>setImportando(!importando)}>↑ Importar estoque</button><select aria-label="Formato de exportação" className="rbk-input" value={formato} disabled={busy} onChange={e=>setFormato(e.target.value as 'xlsx'|'csv')}><option value="xlsx">Excel (.xlsx)</option><option value="csv">CSV (.csv)</option></select><button disabled={busy||!resultado} className={`rbk-primary ${btn}`} onClick={()=>void exportar()}>↓ Exportar planilha</button></div></div>
 <section className="rbk-card p-5" aria-label="Filtros por período"><div className="flex flex-wrap gap-2">{modos.map(([m,label])=><button className={`${btn} ${modo===m?'bg-red-700 text-white':'bg-gray-50 text-gray-600'}`} key={m} disabled={busy} aria-pressed={modo===m} onClick={()=>mudar(m)}>{label}</button>)}<button className={`rbk-secondary ${btn}`} disabled={busy||(modo==='personalizado'&&(!inicio||!fim))} onClick={()=>void buscar(modo,inicio,fim)}>Atualizar</button></div>{modo==='personalizado'&&<form className="mt-4 flex flex-wrap items-end gap-3" onSubmit={e=>{e.preventDefault();void buscar(modo,inicio,fim);}}><label className="text-sm">Data inicial<input className="rbk-input mt-1 block" type="date" required value={inicio} max={fim||periodo('hoje').fim} disabled={busy} onChange={e=>setInicio(e.target.value)}/></label><label className="text-sm">Data final<input className="rbk-input mt-1 block" type="date" required value={fim} min={inicio} max={periodo('hoje').fim} disabled={busy} onChange={e=>setFim(e.target.value)}/></label><button className={`rbk-primary ${btn}`} disabled={busy}>Aplicar período</button></form>}
 {resultado&&<p className="mt-4 text-sm text-gray-500">{dataBr(resultado.p.inicio)} a {dataBr(resultado.p.fim)} · {analise?.dias} dias corridos · {resultado.estoque.nome}</p>}</section>
 {busy&&<p role="status" className="py-5 text-sm text-gray-500">Processando…</p>}{erro&&<p role="alert" className="mt-5 rounded-xl bg-red-50 p-4 text-sm text-red-800">{erro}</p>}{mensagem&&<p role="status" className="mt-4 text-sm text-green-800">{mensagem}</p>}
 {resultado&&analise&&<>{!resultado.dados.estruturaDisponivel&&<p className="mt-5 rounded-xl bg-amber-50 p-4 text-sm text-amber-900">Os itens estruturados das dispensações ainda não estão disponíveis. As projeções aparecerão após a ativação e a confirmação dos itens em Vendas e Indicadores.</p>}
 {!resultado.estoque.base?<p className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><strong>Estoque não importado.</strong> Mostramos somente consumo e projeções disponíveis. Importe o estoque para calcular cobertura e reposição.{!resultado.estoque.farmId?' Seu perfil precisa estar vinculado a uma farmácia para importar.':''}{!resultado.estoque.disponivel?' A estrutura de armazenamento de estoque ainda precisa ser ativada.':''}</p>:<p className="mt-5 rounded-xl bg-white p-4 text-sm text-gray-600"><strong>Estoque informado em {dataBr(resultado.estoque.base.data_posicao)}</strong> · {resultado.estoque.base.arquivo}. Posição importada, sem atualização automática de entradas ou saídas. Reimporte um saldo atual antes de comprar.</p>}
 <p className="mt-3 text-xs leading-5 text-gray-500">Base: dispensações confirmadas das autorizações vinculadas à farmácia selecionada, pela data da autorização. Outras vendas e movimentos da farmácia não estão incluídos. Projeção linear do histórico selecionado, sem ajuste de sazonalidade; não representa a necessidade total da farmácia.</p>
 {(analise.semItens>0||analise.pendentes>0)&&<p className="mt-3 rounded-xl bg-amber-50 p-3 text-sm text-amber-900">Base incompleta: {analise.semItens} autorizações sem itens confirmados e {analise.pendentes} itens pendentes. As projeções disponíveis consideram somente o consumo confirmado e podem subestimar a demanda.</p>}
 {importando&&<ImportarEstoque anterior={!!resultado.estoque.base} onClose={()=>setImportando(false)} onSave={importar}/>}
 <section className="my-6 flex flex-wrap items-end gap-4" aria-label="Critérios de planejamento"><label className="text-sm font-semibold">Unidade dos indicadores<select className="rbk-input mt-2 block" value={atual} onChange={e=>setUn(e.target.value)}>{unidades.length?unidades.map(u=><option key={u} value={u}>{u||'Não informada'}</option>):<option value="">Sem produtos</option>}</select></label><label className="text-sm font-semibold">Horizonte de compra<select className="rbk-input mt-2 block" value={horizonte} onChange={e=>setHorizonte(Number(e.target.value) as 30|60|90)}>{[30,60,90].map(n=><option key={n} value={n}>{n} dias</option>)}</select></label><label className="text-sm font-semibold">Risco de ruptura até<select className="rbk-input mt-2 block" value={risco} onChange={e=>{const v=Number(e.target.value);setRisco(v);setBaixo(Math.max(v,baixo));}}>{[3,7,10,15].map(n=><option key={n} value={n}>{n} dias</option>)}</select></label><label className="text-sm font-semibold">Baixo estoque até<select className="rbk-input mt-2 block" value={baixo} onChange={e=>setBaixo(Number(e.target.value))}>{[7,10,15,30].filter(n=>n>=risco).map(n=><option key={n} value={n}>{n} dias</option>)}</select></label><p className="max-w-sm text-xs leading-5 text-gray-500">Caixas, comprimidos e outras unidades ficam separados. A tabela mantém todas as unidades.</p></section>
 <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4" aria-label="Indicadores">{cards.map(([label,value,nota])=><article key={label} className="rbk-card p-5"><h2 className="text-sm font-semibold text-gray-600">{label}</h2><p className="mt-3 break-words text-2xl font-bold tracking-tight text-gray-900">{value}<small className="ml-2 text-sm font-normal text-gray-400">{atual}</small></p><p className="mt-3 text-xs leading-5 text-gray-500">{nota}</p></article>)}</section>
 <section className="mt-4 grid gap-4 sm:grid-cols-3" aria-label="Projeções de consumo">{([30,60,90] as const).map(n=><div key={n} className="rbk-card p-5"><h2 className="text-sm font-semibold text-gray-600">Consumo projetado · {n} dias</h2><p className="mt-2 text-xl font-bold">{numero(sum(n===30?'projecao30':n===60?'projecao60':'projecao90'))} <small className="font-normal text-gray-400">{atual}</small></p></div>)}</section>
 <div className="mt-5 flex flex-wrap gap-3 text-sm"><span className="rounded-full bg-red-100 px-4 py-2 font-semibold text-red-800">{alertaRuptura} em risco de ruptura</span><span className="rounded-full bg-amber-100 px-4 py-2 font-semibold text-amber-800">{alertaBaixo} com baixo estoque</span><span className="rounded-full bg-gray-200 px-4 py-2 font-semibold text-gray-700">{semCorrespondencia} sem correspondência / identificação</span></div>
 <div className="mt-6 grid gap-5 xl:grid-cols-2"><section className="rbk-card min-w-0 p-6"><h2 className="mb-5 text-lg font-bold">Produtos de maior consumo</h2><Barras produtos={selecionados} campo="consumo" unidade={atual}/></section><section className="rbk-card min-w-0 p-6"><h2 className="mb-5 text-lg font-bold">Cobertura de estoque</h2><Barras produtos={selecionados} campo="cobertura" unidade={atual}/></section><section className="rbk-card min-w-0 p-6"><h2 className="mb-5 text-lg font-bold">Evolução do consumo</h2><EvolucaoCompras pontos={pontos} unidade={atual}/></section><section className="rbk-card min-w-0 p-6"><div className="mb-5 flex flex-wrap justify-between gap-3"><h2 className="text-lg font-bold">Necessidade projetada · {horizonte} dias</h2><select aria-label="Tipo de necessidade projetada" className="rbk-input text-sm" value={necessidade} onChange={e=>setNecessidade(e.target.value as 'projecao'|'compra')}><option value="projecao">Consumo projetado</option><option value="compra">Reposição sugerida</option></select></div><Barras produtos={selecionados} campo={field} unidade={atual}/></section></div>
 <DemandaFutura farmId={farmId}/><TabelaCompras produtos={produtos} horizonte={horizonte}/><details className="mt-6 text-sm text-gray-600"><summary className="cursor-pointer font-semibold">Como calculamos</summary><p className="mt-3 leading-7">Média diária = quantidade confirmada ÷ dias corridos do período, incluindo início e fim. Média mensal = média diária × 30. Cobertura = estoque ÷ média diária. Projeção = média diária × horizonte. Sugestão = projeção menos estoque, com mínimo zero e arredondamento para cima. Consumo zero não gera cobertura infinita. Sem saldo informado ou unidade compatível, não há sugestão de compra. Grupos com quantidade incompleta ou pendente não geram projeção. Estoque sem consumo confirmado permanece sem média estimada.</p></details></>}
 </div></div>;
}

