'use client';
import {useEffect,useState} from 'react';
import {adicionarDias,hojeLocal,type Demanda} from '../../lib/proximas/domain';
import {supabaseRepository,type ProximasRepository} from '../../lib/proximas/repository';
export default function DemandaFutura({farmId,repository=supabaseRepository}:{farmId:string;repository?:ProximasRepository}){
 const [dias,setDias]=useState(30);
 const [resposta,setResposta]=useState<{farmId:string;dias:number;repository:ProximasRepository;data:Demanda|null;erro:string}|null>(null);
 const atual=resposta?.farmId===farmId&&resposta.dias===dias&&resposta.repository===repository?resposta:null;
 const r=atual?.data,erro=atual?.erro||'';
 useEffect(()=>{let active=true;const hoje=hojeLocal();repository.demanda(farmId,adicionarDias(hoje,1),adicionarDias(hoje,dias)).then(data=>{if(active)setResposta({farmId,dias,repository,data,erro:''});}).catch(e=>{if(active)setResposta({farmId,dias,repository,data:null,erro:e instanceof Error?e.message:'Não foi possível consultar a demanda.'});});return()=>{active=false;};},[farmId,dias,repository]);
 return <section className="rbk-card my-6 p-5" aria-label="Demanda futura prevista"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-bold text-gray-900">Demanda futura prevista</h2><label className="text-sm font-semibold">Horizonte<select className="rbk-input ml-2" value={dias} onChange={e=>setDias(Number(e.target.value))}>{[2,7,30].map(n=><option key={n} value={n}>Próximos {n} dias</option>)}</select></label></div><p className="mt-3 text-sm leading-6 text-gray-500">Retiradas agendadas por produto, a partir de amanhã. Esta informação não altera o estoque nem é somada automaticamente à projeção histórica.</p>{erro?<p role="alert" className="mt-4 text-sm text-red-700">{erro}</p>:!r?<p role="status" className="mt-4 text-sm text-gray-500">Consultando previsões…</p>:<>{r.nao_calculadas>0&&<p className="mt-3 text-sm text-amber-800">{r.nao_calculadas} previsões sem data não entram na demanda.</p>}{r.produtos.length?<div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b text-gray-500"><tr>{['Produto / EAN','Unidade','Retiradas','Clientes','Quantidade futura'].map(t=><th className="px-3 py-3" key={t}>{t}</th>)}</tr></thead><tbody>{r.produtos.map(p=><tr className="border-b border-gray-100" key={p.chave+'|'+p.unidade}><td className="px-3 py-3 font-semibold">{p.produto}<span className="block text-xs font-normal text-gray-500">{p.ean||'Sem EAN; mantido separado'}</span></td><td className="px-3 py-3">{p.unidade||'Não informada'}</td><td className="px-3 py-3">{p.retiradas}</td><td className="px-3 py-3">{p.clientes}</td><td className="px-3 py-3">{p.quantidade_estimada??'Não confirmada'}</td></tr>)}</tbody></table></div>:<p className="mt-4 text-sm text-gray-500">Nenhuma demanda prevista neste horizonte.</p>}<p className="mt-4 text-xs leading-5 text-gray-500">A quantidade anterior não determina a quantidade da próxima retirada. Previsões encerradas ou invalidadas ficam fora deste painel.</p></>}</section>;
}
