import fs from 'node:fs';import assert from 'node:assert/strict';import {createClient} from '@supabase/supabase-js';import {createHash} from 'node:crypto';
const base=process.env.CRE_TEST_URL,accounts=JSON.parse(fs.readFileSync('../staging-bootstrap/.accounts.json','utf8')),clients=[];
for(const a of accounts){const c=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,{auth:{persistSession:false}});const {data,error}=await c.auth.signInWithPassword({email:a.email,password:a.password});if(error)throw Error('Test login unavailable');clients.push(data.session.access_token);}
async function api(b,auth){const r=await fetch(base+'/api/credenciamento',{method:'POST',headers:{'Content-Type':'application/json',...(auth?{Authorization:'Bearer '+auth}:{})},body:JSON.stringify(b)});return {status:r.status,data:await r.json()};}
assert.equal((await api({op:'list',manager:true,id:''},clients[0])).status,200);
const ficha={B19:'11.222.333/0001-81',B20:'11.222.333/0001-81',B21:'TESTE SINTÉTICO CREDENCIAMENTO',B32:'teste@example.invalid',B33:'(00) 90000-0000'};
let r=await api({op:'create',manager:true,filial:false,ficha},clients[0]);assert.equal(r.status,200,JSON.stringify(r.data));const id=r.data.id;let token=r.data.link.split('#')[1];fs.writeFileSync('../credenciamento-preview/test-link.json',JSON.stringify({id,link:r.data.link}),{mode:0o600});
assert.equal((await api({op:'get',token})).data.ficha.B19,ficha.B19);assert.equal((await api({op:'get',id,manager:true},clients[1])).status,409);assert.equal((await api({op:'create',manager:true,filial:false,ficha},clients[2])).status,409);assert.equal((await api({op:'get',token:'A'.repeat(43)})).status,409);
assert.equal((await api({op:'save',token,ficha,filial:false,partners:1,revision:1})).status,400);
const fields=JSON.parse(fs.readFileSync('src/lib/processos/fields.json'));const complete=Object.fromEntries(fields.filter(f=>!f.group.startsWith('Sócio ')||f.group==='Sócio 1').map(f=>[f.cell,f.type==='date'?'2027-12-31':/MAIL|ELETRÔNICO/.test(f.label)?'teste@example.invalid':'TESTE']));Object.assign(complete,ficha,{B22:'Salvo'});
r=await api({op:'save',token,ficha:complete,filial:false,partners:1,revision:1});assert.equal(r.status,200);assert.equal((await api({op:'save',token,ficha:complete,filial:false,partners:1,revision:1})).status,409);assert.equal((await api({op:'get',token})).data.ficha.B22,'Salvo');
const bytes=fs.readFileSync('../credenciamento-preview/test.png'),file={id:crypto.randomUUID(),name:'documento-sintetico.png',kind:0,mime:'image/png',size:bytes.length,fingerprint:createHash('sha256').update(bytes).digest('hex')};
r=await api({op:'init',token,file});assert.equal(r.status,200,JSON.stringify(r.data));const fid=r.data.id;const upload=await fetch(r.data.url,{method:'PUT',headers:{'Content-Type':'image/png','x-upsert':'false'},body:bytes});assert(upload.ok,'Upload '+upload.status);r=await api({op:'confirm',token,fileId:fid});assert.equal(r.status,200,JSON.stringify(r.data));assert.equal(r.data.files.length,1);assert.equal((await api({op:'init',token,file})).data.received,true);assert.equal((await api({op:'file',id,manager:true,fileId:fid},clients[0])).status,200);assert.equal((await api({op:'file',token,fileId:fid})).status,403);
r=await api({op:'renew',id,manager:true},clients[0]);assert.equal(r.status,200);assert.equal((await api({op:'get',token})).status,409);token=r.data.link.split('#')[1];assert.equal((await api({op:'get',token})).status,200);await api({op:'revoke',id,manager:true},clients[0]);assert.equal((await api({op:'get',token})).status,409);
const anon=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY);assert((await anon.from('cre_processes').select('id')).error);const html=await (await fetch(base+'/portal/credenciamento')).text();assert(html.includes('async function api(op'));console.log('PASS: create/save/reopen/conflict/upload/dedup/private/RBAC/cross-owner/revoke/renew/HTML');
